"""Process exit codes returned by the CLI."""

SUCCESS = 0
ERROR_GENERAL = 1
USER_CTRL_C = 2
USER_CTRL_BREAK = 3
ERROR_SIGTERM = 4
ERROR_INVALID_CONFIGURATION = 5
ERROR_UNEXPECTED = 6
ERROR_ENCOUNTERED = 7
