"""Markdown SqlEmitter — produces a documentation file instead of SQL.

This emitter intentionally bends the ``SqlEmitter`` Protocol: it writes
Markdown rather than SQL, demonstrating that the port is dialect-agnostic and
the only contract is the sequence of ``emit_*`` calls.

Each schema becomes an ``##`` section, each table a ``###`` subsection with a
column table and, when sample rows are available, a small preview block.
"""

from __future__ import annotations

from typing import Any, Iterable, List, Mapping, Optional

from db2sql.application.ports import OutputSink
from db2sql.domain.model import Database, Schema, Table


class MarkdownEmitter:
    """Emit a Markdown documentation file from a collected :class:`Database`."""

    def __init__(
        self,
        preserve_case: bool = False,
        schema_mapping: Optional[Mapping[str, str]] = None,
    ) -> None:
        # Both kwargs accepted for API compatibility with the built-in emitters;
        # neither is meaningful for Markdown output, so we ignore them.
        self._preserve_case = preserve_case
        self._schema_mapping = schema_mapping or {}

    # ---- structural sections ---------------------------------------------

    def emit_prologue(self, sink: OutputSink) -> None:
        sink.write("# Database documentation\n\n")
        sink.write("_Generated by db2sql + the `markdown` emitter plugin._\n\n")

    def emit_epilogue(self, sink: OutputSink) -> None:
        sink.write("\n---\n")

    def emit_schemas(self, database: Database, sink: OutputSink) -> None:
        sink.write(f"Database: **{database.name}**\n\n")

    def emit_tables(self, database: Database, sink: OutputSink) -> None:
        for schema in database.schemas.values():
            sink.write(f"## Schema `{schema.name}`\n\n")
            for table in schema.tables.values():
                self._emit_table_header(schema, table, sink)

    def _emit_table_header(self, schema: Schema, table: Table, sink: OutputSink) -> None:
        sink.write(f"### `{schema.name}.{table.name}`\n\n")
        sink.write("| Column | Type | Nullable | Default | Notes |\n")
        sink.write("|---|---|---|---|---|\n")
        for column in table.columns.values():
            notes: List[str] = []
            if column.is_primary_key:
                notes.append("PK")
            if column.foreign_key:
                fk = column.foreign_key
                notes.append(f"FK → `{fk.schema}.{fk.table}.{fk.column}`")
            type_repr = column.type
            if column.char_length and column.char_length > 0:
                type_repr = f"{type_repr}({column.char_length})"
            sink.write(
                f"| `{column.name}` | `{type_repr}` | "
                f"{'yes' if column.nullable else 'no'} | "
                f"{column.default if column.default is not None else ''} | "
                f"{', '.join(notes)} |\n"
            )
        sink.write("\n")

    def emit_foreign_keys(self, database: Database, sink: OutputSink) -> None:
        # Already inlined in the column table; nothing extra to emit.
        return

    def emit_indexes(self, database: Database, sink: OutputSink) -> None:
        any_index = False
        buffer = ["## Indexes\n\n"]
        for schema in database.schemas.values():
            for table in schema.tables.values():
                for index_name, columns in table.indexes.items():
                    any_index = True
                    cols = ", ".join(f"`{c}`" for c in columns)
                    buffer.append(
                        f"- `{schema.name}.{table.name}` → **{index_name}** ({cols})\n"
                    )
        if any_index:
            sink.write("".join(buffer))
            sink.write("\n")

    # ---- data ------------------------------------------------------------

    def emit_data_copy(
        self,
        schema: Schema,
        table: Table,
        rows: Iterable[Iterable[Any]],
        sink: OutputSink,
    ) -> None:
        # No COPY in Markdown — render the same preview as emit_data_insert.
        self.emit_data_insert(schema, table, rows, sink)

    def emit_data_insert(
        self,
        schema: Schema,
        table: Table,
        rows: Iterable[Iterable[Any]],
        sink: OutputSink,
    ) -> None:
        sample = list(rows)
        if not sample:
            return
        sink.write(f"#### Sample rows — `{schema.name}.{table.name}`\n\n")
        header = " | ".join(table.columns)
        separator = " | ".join("---" for _ in table.columns)
        sink.write(f"| {header} |\n| {separator} |\n")
        for row in sample[:10]:
            cells = " | ".join("" if v is None else str(v) for v in row)
            sink.write(f"| {cells} |\n")
        if len(sample) > 10:
            sink.write(f"\n_… {len(sample) - 10} more rows omitted._\n")
        sink.write("\n")
